# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ddffbaf80557bd4574e8ae7150bf2a1e1759fa9e17698d07bbcde73547062b4e871be500b5fef0ab1ef8661d956109701c525403fda5a30b089a030797e92e

test:
  secret_key_base: efb272dab05a76209ee37aa6b54fb1e624d85cb6ed4735baa2093d1cae7e42a4e97a413b501a251f4fe4ccc5313cf362a9cbe3bd479b4632b659bd753022fbab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
